# Generated by Django 5.1.7 on 2025-04-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='incorrect_questions',
            field=models.ManyToManyField(blank=True, to='quizzes.question'),
        ),
    ]
