# Generated by Django 5.1.7 on 2025-04-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quizattempt_incorrect_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='incorrect_questions',
            field=models.ManyToManyField(blank=True, help_text='Incorrect questions', to='quizzes.question'),
        ),
    ]
